on: pull_request

jobs:
  dvc-feature-flag-insights:
    runs-on: ubuntu-latest
    name: Generate DevCycle PR Insights
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DevCycleHQ/feature-flag-pr-insights-action@main
        with:
          github-token: ${{ secrets.AUTOMATION_USER_TOKEN }}
          project-key: audience-test-project
          client-id: ${{ secrets.DVC_CLIENT_ID }}
          client-secret: ${{ secrets.DVC_CLIENT_SECRET }}
